<template><h1 id="最常问的问题" tabindex="-1"><a class="header-anchor" href="#最常问的问题" aria-hidden="true">#</a> 最常问的问题</h1>
<h2 id="傻子问题" tabindex="-1"><a class="header-anchor" href="#傻子问题" aria-hidden="true">#</a> 傻子问题</h2>
<blockquote>
<p>Q:怎么使用内网穿透？</p>
</blockquote>
<blockquote>
<p>A:先这样在那样</p>
<p>对于这种不看Wiki的人，我们为他们准备了一个价目表：</p>
<table>
<thead>
<tr>
<th>描述</th>
<th>价格</th>
</tr>
</thead>
<tbody>
<tr>
<td>包含“救命呀”等词汇，无截图，无日志，态度恶劣</td>
<td>不予解决</td>
</tr>
<tr>
<td>包含“救命呀”等词汇，无截图，无日志</td>
<td>2000￥</td>
</tr>
<tr>
<td>无截图，无日志，语气诚恳</td>
<td>1000￥</td>
</tr>
<tr>
<td>有截图，无日志</td>
<td>500￥</td>
</tr>
<tr>
<td>有截图，有部分日志</td>
<td>200￥</td>
</tr>
<tr>
<td>有截图，有日志</td>
<td>100￥</td>
</tr>
<tr>
<td>有截图，有日志，有简略描述</td>
<td>50￥</td>
</tr>
<tr>
<td>有截图，有日志，有详细的描述</td>
<td>免费，尽可能帮助解决</td>
</tr>
</tbody>
</table>
</blockquote>
<blockquote>
<p>Q:我的客户端出问题了，能帮帮我吗？</p>
</blockquote>
<blockquote>
<p>A:好的，还要帮你拍背和换尿布吗？</p>
</blockquote>
<blockquote>
<p>Q:他让我加启动参数，怎么加啊？</p>
</blockquote>
<blockquote>
<p>A:我的天哪，都2022年了不会还有人不会用百度吧？</p>
</blockquote>
<blockquote>
<p>Q:怎么装 Java 啊？</p>
</blockquote>
<blockquote>
<p>A:建议重看Wiki</p>
</blockquote>
<h2 id="节点相关" tabindex="-1"><a class="header-anchor" href="#节点相关" aria-hidden="true">#</a> 节点相关</h2>
<blockquote>
<p>Q:我除了xxx节点之外其他的节点都显示EOF，这是怎么回事？[截图]</p>
</blockquote>
<blockquote>
<p>A:首先，请检查你的防火墙和杀毒软件<br>
第二，检查你的路由器和网关<br>
第三，尝试ping和nslookup节点地址<br>
如果无效，建议直接换运营商</p>
</blockquote>
<blockquote>
<p>Q:我尝试连接的节点无法连接，显示no such host</p>
</blockquote>
<blockquote>
<p>A:请尝试更换DNS</p>
</blockquote>
<blockquote>
<p>Q:我无法连接到节点，显示连接超时！</p>
</blockquote>
<blockquote>
<p>A:首先，请检查你的网路连接<br>
如果网络正常，看看群里<br>
如果大家都连不上，这代表节点出现故障，请等待或者退款</p>
</blockquote>
<blockquote>
<p>Q:节点为什么需要金币才能购买？</p>
</blockquote>
<blockquote>
<p>A:这代表这个节点是收费节点，在群内回复#充值自助购买卡密后使用后#卡密激活卡密，然后继续购买</p>
</blockquote>
<h2 id="客户端相关" tabindex="-1"><a class="header-anchor" href="#客户端相关" aria-hidden="true">#</a> 客户端相关</h2>
<blockquote>
<p>Q:怎么使用客户端？</p>
</blockquote>
<blockquote>
<p>A:help</p>
</blockquote>
<blockquote>
<p>Q:客户端无响应了？</p>
</blockquote>
<blockquote>
<p>A:它在连接节点，如果长时间无响应请重启客户端</p>
</blockquote>
<blockquote>
<p>Q:<s>我遇到了一个Bug（感谢群友@XvMC_XingYe提供）<img src="https://crabpic.oss-cn-qingdao.aliyuncs.com/2022/01/20/80BED2F09C9141DFAEC7C3F29EF7C83D.png" alt="80BED2F09C9141DFAEC7C3F29EF7C83D.png">（该Bug已在V0.5.12.1512修复）</s></p>
</blockquote>
<blockquote>
<p>A:<s>反馈给墨守，如果是最新版降级，老版本升级</s></p>
</blockquote>
<blockquote>
<p>Q:GUI客户端什么时候出？</p>
</blockquote>
<blockquote>
<p>A:在做了在做了（别催了呜呜呜</p>
</blockquote>
</template>
